# Generated by Django 3.2.5 on 2021-07-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw6', '0002_alter_new_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='bools',
            field=models.BooleanField(default=False),
        ),
    ]
