# Generated by Django 3.2.5 on 2021-07-05 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hw6', '0003_favourite_bools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='link_to_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='hw6.new'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
